### ISSUE TITLE
编译latex遇到错误。

### ISSUE THREAD

**Issue by cauzp** [HKFoggyU/hkust-thesis#10]
![Snipaste_2023-12-07_16-27-21](https://github.com/HKFoggyU/hkust-thesis/assets/57480596/b8b88ab9-4806-4165-9091-ac56c1f60f09)
在进行编译时，vs code中的command命令无法正常编译latex。具体情况如图所示。

**Comment by github-young** [comment]
Can you provide more compiler log?
