### ISSUE TITLE
Error in algorithm environment

### ISSUE THREAD

**Issue by AJohn11** [HKFoggyU/hkust-thesis#11]
For example, this code will have an error: `algorithm.sty:96: LaTeX Error: Command \c@algorithm already defined. [\floatname]`
```
\begin{algorithm}
\caption{1}
\label{alg:1}
\begin{algorithmic}
\end{algorithmic}
\Require 1
\Ensure 1
\end{algorithm}
```
**Solution:**
We can solve the problem by commenting the following part in `hkustthesis.cls`: 
```
\declaretheorem[
    name=Algorithm,
    style=hkustthm,
    refname={algorithm,algorithms},
    Refname={Algorithm,Algorithms},
    % numberwithin=section,
]{algorithm}
```
Then we can add a line `\listofalgorithms` after 
```
\listoffigures
\listoftables
```
in the front, which will have a list page of all the algorithms in the thesis, just like the list page of all the figures from `\listoffigures`.

**Comment by github-young** [comment]
Thank you. This issue originated from the historical code (see https://github.com/nju-lug/NJUThesis/issues/49). I made the changes accordingly. Please refer to the latest release. You can replace the latest `.cls` file with the old one and it won't break the main file.

However, the default `listofalgorithms` environment is a bit inconsistent with the overall **style** of its counterparts, so I tried my best to make a similar implementation but still had some issues. Hope someone in the future can help achieve a full implementation.
