### ISSUE TITLE
Citation has `(visited on day/month/year)` in each item of the References

### ISSUE THREAD

**Issue by AJohn11** [HKFoggyU/hkust-thesis#12]
Citation has `(visited on day/month/year)` in each item of the References.

**Solution:**
Add the following part in `hkustthesis.cls`: 
```
\AtEveryBibitem{
    \clearfield{urlyear} % add
    \clearfield{urlmonth} % add
}
```

**Comment by github-young** [comment]
Thank you. Fixed in 5fdff9b7d653c85a1fab4a7468d6cde9bfdc2988
