### ISSUE TITLE
Github Workflow Update

### ISSUE THREAD

**Issue by zybbigpy** [HKFoggyU/hkust-thesis#5]
Hello Young,

Now, we have a nice workflow to make the things automatically run. I think we may need to split the workflow into three different files to make the whole process smooth and clear:

1. `test workflow`, when contributors file a pull request, it will automatically run some tests to ensure the compilation is OK. It should be triggered automatically.
2. `build workflow`, some advanced users may directly fork the repo, write their thesis and organize it through GitHub. We can provide a build workflow to construct their thesis online and return a PDF file. It can be triggered manually.
3. `release workflow`, when we tag the commit as a release, GitHub Actions will help us release the new version of HKUST thesis template. It should be triggered automatically.

**Comment by github-young** [comment]
I am new to GitHub Actions. Can you help on it?

**Comment by github-young** [comment]
I will take task 3.

**Comment by zybbigpy** [comment]
Yes, I will do task 1&2

**Comment by github-young** [comment]
Closed in #6
