### ISSUE TITLE
Blank pages

### ISSUE THREAD

**Issue by HaFred** [HKFoggyU/hkust-thesis#9]
Hi @github-young , thank you very much for contributing such a great template for the UST community. I just have a question regarding the blank pages at around toc, lof, lot, etc., is it required to have these blank pages? Also, how can I remove them? I tried to remove all `\clearpage` and `\cleardoublepage` in `hkustthesis.cls`, but it seemed to be not working...

Thanks in advance!

**Comment by github-young** [comment]
Hi thank you. These blank pages are not required explicitly by the RPG handbook, but it is a common practice in typesetting books (thesis).

This is a newly-added feature.
You can disable the blank pages by changing the config term `blankpages = false` in the document options. You can refer to the PDF documentation `hkustthese-v0.7.4.pdf` in the latest release.

**Comment by github-young** [comment]
I also uploaded it to Overleaf, but it has not been approved. You can either wait for its approval (probably next Monday) or download all the files in GitHub and then upload them onto your Overleaf project (overwriting the files)

**Comment by github-young** [comment]
That should be done by the `twoside` term in document options passed to `book` documentclass defined in `LoadClass` line
